
name: Organize Branch

on:
  push:
    branches:
      - main

jobs:
  organize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '<>'

      - name: Create a specific branch for frontend folder
        run: |
          git checkout -b frontend
          git worktree add -B frontend ../frontend origin/frontend

      - name: Create backend branch API Indice Pluviometrico
        run: |
          git checkout -b backend-api-indice-pluviometrico
          git worktree add -B backend-api-indice-pluviometrico ../backend-api-indice-pluviometrico origin/backend-api-indice-pluviometrico


