
name: Organize Branch

on:
  push:
    branches:
      - main

jobs:
  organize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '<>'

      - name: Create frontend branch
        run: |
          git checkout -b frontend
          git add frontend/*
          git commit -m "Sync frontend"
          git push --set-upstream origin frontend

      - name: Create backend branch API Indice Pluviometrico
        run: |
          git checkout -b backend-api-indice-pluviometrico
          git add backend/api-indice-pluviometrico/*
          git commit -m "Sync backend api indice pluviometrico"
          git push --set-upstream origin backend-api-indice-pluviometrico
